export const QUESTION_DESCRIPTIONS: Record<string, string> = {
  "Peralatan Kerja - Ergonomi": "Desain peralatan kerja sesuai postur tubuh, mudah dijangkau, tidak menyebabkan posisi kerja membungkuk atau menjangkau berlebihan, serta mendukung kenyamanan dan keselamatan kerja",
  "Peralatan Kerja - Penempatan Teratur dan 5R": "Alat dan barang ditata sesuai jenis dan fungsinya, mudah diambil dan dikembalikan, tidak ada barang yang tidak diperlukan, area kerja bersih, rapi, sesuai prinsip 5R",
  "Peralatan Medik - Berfungsi baik": "Alat dalam kondisi utuh, dapat dioperasikan tanpa kerusakan fisik yang tampak, serta siap digunakan",
  "Peralatan Medik - Kartu/Label kalibrasi masih berlaku": "Terdapat kartu/label yang menunjukkan bahwa alat medis telah dikalibrasi dan masih berlaku, memuat tanggal kalibrasi dan masa berlaku.",
  "APAR - Terjangkau": "APAR mudah dijangkau, tidak terhalang oleh barang lain, dan dapat diakses dengan cepat dalam kondisi darurat",
  "APAR - Rambu dan SOP terpasang": "Tanda/label lokasi APAR dan Panduan Penggunaan APAR dipasang di dekat alat secara jelas, terlihat, dan mudah dibaca oleh semua pengguna",
  "APAR - Kartu pemeliharaan terisi": "Terdapat tanggal pemeriksaan, status fungsi, dan tanda tangan petugas, yang diisi setiap bulan",
  "Hydrant - Box tersedia dan lengkap": "Kotak hydrant berisi selang, nozzle, valve, dan wrench dalam kondisi baik dan siap pakai",
  "Hydrant - SOP terpasang": "Petunjuk tertulis cara penggunaan hydrant terpasang, terlihat dan mudah dibaca",
  "Hydrant - Fire alarm": "Terdapat sistem deteksi dan peringatan dini kebakaran, mudah dijangkau, dan berfungsi",
  "Hydrant - Terdapat kartu pemeliharaan berlaku": "Kartu pemeliharaan hydrant masih berlaku",
  "Sarana Proteksi Kebakaran - Smoke Detector/Heat Detector": "Detector terpasang utuh, tidak lepas dari dudukan, tidak tertutup, tidak berdebu",
  "Sarana Proteksi Kebakaran - Sprinkler": "Sprinker utuh, tidak patah, tidak bocor, tidak berkarat, tidak tertutup debu, bebas halangan",
  "Rambu Keselamatan - Jalur evakuasi": "Rambu jalur evakuasi (jelas, terlihat, sesuai arah keluar)",
  "Rambu Keselamatan - Exit/keluar": "Rambu \"exit\"/\"keluar\" jelas dan terlihat pada pintu darurat/akses evakuasi (tangga darurat dan ramp)",
  "Rambu Keselamatan - Peringatan": "Terdapat rambu sesuai risiko area (hati-hati terpeleset / hati-hati terjatuh / ruang khusus / area berbahaya, dll)",
  "Rambu Keselamatan - Hati-hati tersandung (pilih N/A, jika tidak ada lantai beda ketinggian)": "Terdapat rambu hati-hati tersandung/hati-hati terjatuh pada lantai beda ketinggian (Khusus ruangan yang ada lantai beda ketinggian)",
  "Rambu Keselamatan - Peta evakuasi": "Peta evakuasi terpasang di area strategis dan terlihat, yang menunjukkan arah jalur evakuasi, posisi titik kumpul dan lokasi alat pemadam",
  "Rambu Keselamatan - Bis pada anak tangga (Pilih N/A, jika tidak ada tangga)": "Tanda kontras di tepi anak tangga untuk mencegah tersandung atau salah langkah (khusus ruangan yang memiliki tangga)",
  "Rambu Keselamatan - Titik kumpul (Selain IGD dan Singgalang 1, pilih N/A)": "Tanda lokasi berkumpul saat evakuasi jelas terlihat dan tidak tertutup",
  "Rambu Keselamatan - Dilarang merokok": "Tanda larangan merokok yang jelas",
  "Rambu Keselamatan - Hemat listrik/air": "Himbauan visual untuk menghemat energi",
  "Elektrik - Perkabelan aman": "Kabel rapi, terlindungi, tidak rusak, tidak membahayakan petugas",
  "Elektrik - Sumber dan sambungan listrik aman": "Stop kontak tidak menumpuk, jauh dari air/wastafel",
  "Jalur Evakuasi - Bebas hambatan": "Jalur Evakuasi (koridor, tangga, pintu, ramp) dapat dilalui/tidak ada benda yang menghalangi (brankar, troli, dan barang lainnya)",
  "Jalur Evakuasi - Pintu darurat berfungsi (Pilih N/A, jika tidak ada pintu darurat)": "Pintu darurat berfungsi baik dan tidak terkunci/mudah dibuka saat terjadi keadaan darurat",
  "Keamanan Sarana - Dinding Aman": "Dinding/tembok bersih, tidak berjamur, tidak retak, tidak rembes, dan cat tidak mengelupas",
  "Keamanan Sarana - Pintu/jendela Aman": "Pintu/jendela bersih, mudah dibuka dan ditutup, tersedia kunci, dan hook dalam keadaan aman",
  "Keamanan Sarana - Lantai Aman": "Lantai/keramik bersih, tidak retak, tidak pecah, permukaan rata",
  "Keamanan Sarana - Plafon Aman": "Plafon/atap bersih, tidak bocor, tidak berjamur, tidak mengelupas",
  "Keamanan Sarana - Lampu berfungsi": "Lampu menyala dengan baik",
  "Keamanan Sarana - Ventilasi tersedia": "Terdapat ventilasi yang memadai (Alami/AC/Exhaust Fan)",
  "Keamanan Sarana - Tidak ada puntung rokok": "Tidak ditemukan puntung rokok di sekitar ruangan",
  "Risiko Kecelakaan - Anak tangga aman (pilih N/A, jika tidak ada tangga)": "Tidak licin/tidak berlobang, tidak membahayakan pengguna (khusus ruangan yang memiliki tangga)",
  "Risiko Kecelakaan - Lantai aman": "Tidak licin/tidak ada tumpahan/tidak berlobang dan aman dilalui",
  "Risiko Kecelakaan - Jalur Ramp aman (Selain Singgalang Lt2, Singgalang Lt3 dan Poli Lt 2, pilih N/A)": "Tidak licin/tidak berlubang/tidak rusak (Khusus Singgalang Lt 2, Singgalang Lt 3, dan Poli Lt 2)",
  "Risiko Kecelakaan - Penempatan alat aman": "Penempatan alat/barang dalam posisi aman, disusun stabil, tidak menumpuk berlebihan, tidak berisiko jatuh/tertimpa/terjepit",
  "APD - Ketersediaan terpenuhi": "Alat Pelindung Diri tersedia sesuai jenis pekerjaan, dalam kondisi baik, bersih dan siap digunakan",
  "APD - Karyawan menggunakan APD sesuai": "Setiap petugas memakai APD sesuai potensi bahaya pekerjaan dan menggunakannya dengan benar",
  "Sampah - Sampah sesuai label": "Isi sampah sesuai dengan label tempat sampah (Hijau/Kuning/Abu-abu/Merah/Safety Box)",
  "Code Red - Papan kondisi baik": "Papan utuh, tulisan jelas, tidak kotor, terpasang di lokasi yang mudah terlihat",
  "Code Red - Helm merah kondisi baik": "Layak pakai, tidak retak, bersih, tali pengaman berfungsi",
  "Code Red - Helm putih kondisi baik": "Layak pakai, tidak retak, bersih, tali pengaman berfungsi",
  "Code Red - Helm biru kondisi baik": "Layak pakai, tidak retak, bersih, tali pengaman berfungsi",
  "Code Red - Helm kuning kondisi baik": "Layak pakai, tidak retak, bersih, tali pengaman berfungsi",
  "Code Red - Papan terisi tanggal dan nama": "Kolom tanggal dan nama petugas terisi sesuai jadwal pengecekan",
  "PCRA - Sosialisasi K3 dari kontraktor": "Pekerja mendapatkan sosialisasi K3 dari Kontraktor",
  "PCRA - Pekerja menggunakan APD lengkap": "Pekerja menggunakan APD lengkap sesuai pekerjaan",
  "PCRA - Pembatasan area (barrier)": "Terdapat pembatasan area (barrier) pada lokasi pembangunan/renovasi",
  "PCRA - Rambu keselamatan terpasang": "Rambu keselamatan terpasang pada lokasi pekerjaan",
  "PCRA - Tidak ada pekerja merokok": "Tidak ada pekerja yang merokok di area rumah sakit",
  "PCRA - Tempat material rapi dan bersih": "Material tersusun rapi dan bersih, tidak membahayakan pekerja, pengunjung maupun karyawan",
  "PCRA - Pembersihan sisa pekerjaan": "Pekerja melakukan pembersihan sisa pekerjaan/puing setiap setelah bekerja",
  "Luar Gedung - Terjangkau": "APAR luar ditempatkan pada posisi mudah dijangkau, tidak terhalang oleh barang, tanaman, atau kendaraan di area luar gedung, dan dapat diakses dengan cepat dalam kondisi darurat",
  "Luar Gedung - Rambu dan SOP Terpasang": "Tanda/label lokasi APAR luar dan panduan penggunaan APAR dipasang di dekat alat secara jelas, terlihat, dan mudah dibaca oleh semua orang di area luar gedung",
  "Luar Gedung - Kartu pemeliharaan terisi": "Kartu yang mencatat pemeriksaan rutin APAR luar, termasuk tanggal pemeriksaan, status fungsi, dan tanda tangan petugas, yang diisi setiap bulan sesuai jadwal pemeliharaan",
  "B3 - Penyimpanan Terpisah": "Penyimpanan B3 dilakukan secara terpisah dengan Non B3",
  "B3 - Ketersediaan SDS": "Tersedia SDS (Safety Data Sheet) di lemari penyimpanan B3",
  "B3 - Ketersediaan Spill Kit": "Tersedia Spill Kit khusus untuk menangani tumpahan B3 dan/atau cairan infeksius",
  "B3 - Kelengkapan Spill Kit": "Isi di dalam kotak Spill Kit dalam kondisi lengkap, belum kedaluwarsa, dan siap digunakan saat darurat",
  "B3 - Eyewasher berfungsi baik": "Eyewasher berfungsi dengan baik dan air mengalir lancar",
  "B3 - Bodywasher berfungsi baik": "Bodywasher berfungsi dengan baik dan air mengalir lancar"
};
